# Generated by Django 3.2.7 on 2021-11-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('assignments', '0002_initial'),
        ('playbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPlaybook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='playbookvideoblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='playbooks.playbookassignmentblock'),
        ),
        migrations.AddField(
            model_name='playbooktextblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='playbooks.playbookassignmentblock'),
        ),
        migrations.AddField(
            model_name='playbookquestionblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='playbooks.playbookassignmentblock'),
        ),
        migrations.AddField(
            model_name='playbookoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='playbooks.playbookquestionblock'),
        ),
        migrations.AddField(
            model_name='playbookimageblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='playbooks.playbookassignmentblock'),
        ),
        migrations.AddField(
            model_name='playbookassignmentblock',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='playbooks.playbookassignment'),
        ),
        migrations.AddField(
            model_name='playbookassignment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assignments.category'),
        ),
        migrations.AddField(
            model_name='playbookassignment',
            name='dependent_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbookassignment'),
        ),
        migrations.AddField(
            model_name='playbookassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
