# Generated by Django 3.2.7 on 2021-12-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playbooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbookassignment',
            name='dependent_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playbooks.playbookassignment'),
        ),
        migrations.AlterField(
            model_name='playbookassignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
