# Generated by Django 3.2.7 on 2021-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0003_auto_20211201_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbookassignment',
            name='time',
            field=models.PositiveIntegerField(help_text='Time in seconds', null=True),
        ),
    ]
