# Generated by Django 3.2.7 on 2021-12-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0004_alter_playbookassignment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookassignment',
            name='completed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
