# Generated by Django 3.2.7 on 2021-11-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='assignments.assignmentblock'),
        ),
        migrations.AddField(
            model_name='questionblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='assignments.assignmentblock'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignments.questionblock'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='assignments.assignmentblock'),
        ),
        migrations.AddField(
            model_name='assignmentblock',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assignments.category'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='dependent_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target', to='assignments.assingmenttarget'),
        ),
        migrations.AlterUniqueTogether(
            name='userassignment',
            unique_together={('user', 'assignment')},
        ),
    ]
