# Generated by Django 3.2.7 on 2021-11-12 15:54

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(default='assignments/images/default.jpeg', null=True, upload_to=app.utils.upload_image_path, verbose_name='Tile Image'),
        ),
    ]
