# Generated by Django 3.2.7 on 2021-11-23 07:11

import app.utils
import assignments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblock',
            name='video',
            field=models.FileField(blank=True, upload_to=app.utils.upload_video_path, validators=[assignments.validators.FileValidator(content_types=('video/mpg', 'video/mp2', 'video/mpeg', 'video/mpe', 'video/mpv', 'video/mp4', 'video/m4p', 'video/m4v', 'video/qt', 'video/mov', 'video/wmv', 'video/flv', 'video/avi', 'video/mkv', 'video/quicktime'))]),
        ),
    ]
