# Generated by Django 3.2.7 on 2021-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_videoblock_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in seconds', null=True),
        ),
    ]
