# Generated by Django 3.2.7 on 2021-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingmenttarget',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, default=99, null=True),
        ),
    ]
