# Generated by Django 3.2.7 on 2021-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assingmenttarget_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
